DROP TABLE IF EXISTS `t_alliance`;
CREATE TABLE `t_alliance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '用户id',
  `invitor_alliance_id` int(11) DEFAULT NULL COMMENT '邀请人id',
  `alliance_ship` int(11) NOT NULL DEFAULT '0' COMMENT '是否为盟友 0:否，1:临时，2:正式',
  `stockholder_ship` int(11) NOT NULL DEFAULT '0' COMMENT '是否为股东 0:否，1:是',
  `creation_time` datetime DEFAULT NULL COMMENT 'creation_time',
  `alliance_ship_time` datetime DEFAULT NULL COMMENT '成为盟友的时间',
  `stockholder_ship_time` datetime DEFAULT NULL COMMENT '成为股东的时间',
  `temp_alliance_expiry_time` datetime DEFAULT NULL COMMENT '临时盟友过期时间',
  `alliance_status` int(11) NOT NULL DEFAULT '0' COMMENT '盟友状态，0:禁止，1:正常',
  `alliance_inventory_amount` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '库存金额',
  `alliance_point` decimal(10,4) NOT NULL DEFAULT '0.0000' COMMENT '积分',
  `alliance_rank` int(11) NOT NULL DEFAULT '0' COMMENT '推荐排名',
  `alliance_name` varchar(10) NOT NULL COMMENT '盟友姓名',
  `alliance_sex` int(1) DEFAULT NULL COMMENT '性别',
  `alliance_occupation` varchar(10) DEFAULT NULL COMMENT '职业',
  `alliance_industry` varchar(10) DEFAULT NULL COMMENT '行业',
  `alliance_address` varchar(50) DEFAULT NULL COMMENT '居住地',
  `alliance_business` varchar(10) DEFAULT NULL COMMENT '业务方向',
  `alliance_hobby` varchar(50) DEFAULT NULL COMMENT '兴趣爱好',
  `alliance_phone` varchar(11) DEFAULT NULL COMMENT '电话',
  `alliance_dob` datetime DEFAULT NULL COMMENT '生日',
  `starting_cycle` datetime DEFAULT NULL COMMENT '起算周期',
  `balance` decimal(10,4) DEFAULT NULL COMMENT '去年结余',
  `alliance_type` int(1) DEFAULT NULL COMMENT '1分红盟友，2平台盟友',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;